//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace StringParser
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StringParserEntitiesSchemas : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StringParserEntitiesSchemas object using the connection string found in the 'StringParserEntitiesSchemas' section of the application configuration file.
        /// </summary>
        public StringParserEntitiesSchemas() : base("name=StringParserEntitiesSchemas", "StringParserEntitiesSchemas")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StringParserEntitiesSchemas object.
        /// </summary>
        public StringParserEntitiesSchemas(string connectionString) : base(connectionString, "StringParserEntitiesSchemas")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StringParserEntitiesSchemas object.
        /// </summary>
        public StringParserEntitiesSchemas(EntityConnection connection) : base(connection, "StringParserEntitiesSchemas")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Schema> Schemas
        {
            get
            {
                if ((_Schemas == null))
                {
                    _Schemas = base.CreateObjectSet<Schema>("Schemas");
                }
                return _Schemas;
            }
        }
        private ObjectSet<Schema> _Schemas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SchemaFields> SchemasFields
        {
            get
            {
                if ((_SchemasFields == null))
                {
                    _SchemasFields = base.CreateObjectSet<SchemaFields>("SchemasFields");
                }
                return _SchemasFields;
            }
        }
        private ObjectSet<SchemaFields> _SchemasFields;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Schemas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSchemas(Schema schema)
        {
            base.AddObject("Schemas", schema);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SchemasFields EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSchemasFields(SchemaFields schemaFields)
        {
            base.AddObject("SchemasFields", schemaFields);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StringParserModel", Name="Schema")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Schema : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Schema object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Schema CreateSchema(global::System.Int32 id, global::System.String name)
        {
            Schema schema = new Schema();
            schema.Id = id;
            schema.Name = name;
            return schema;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StringParserModel", Name="SchemaFields")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SchemaFields : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SchemaFields object.
        /// </summary>
        /// <param name="schema">Initial value of the Schema property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="start">Initial value of the Start property.</param>
        /// <param name="length">Initial value of the Length property.</param>
        public static SchemaFields CreateSchemaFields(global::System.Int32 schema, global::System.String name, global::System.Int32 start, global::System.Int32 length)
        {
            SchemaFields schemaFields = new SchemaFields();
            schemaFields.Schema = schema;
            schemaFields.Name = name;
            schemaFields.Start = start;
            schemaFields.Length = length;
            return schemaFields;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Schema
        {
            get
            {
                return _Schema;
            }
            set
            {
                if (_Schema != value)
                {
                    OnSchemaChanging(value);
                    ReportPropertyChanging("Schema");
                    _Schema = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Schema");
                    OnSchemaChanged();
                }
            }
        }
        private global::System.Int32 _Schema;
        partial void OnSchemaChanging(global::System.Int32 value);
        partial void OnSchemaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Start
        {
            get
            {
                return _Start;
            }
            set
            {
                if (_Start != value)
                {
                    OnStartChanging(value);
                    ReportPropertyChanging("Start");
                    _Start = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Start");
                    OnStartChanged();
                }
            }
        }
        private global::System.Int32 _Start;
        partial void OnStartChanging(global::System.Int32 value);
        partial void OnStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private global::System.Int32 _Length;
        partial void OnLengthChanging(global::System.Int32 value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vaules
        {
            get
            {
                return _Vaules;
            }
            set
            {
                OnVaulesChanging(value);
                ReportPropertyChanging("Vaules");
                _Vaules = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vaules");
                OnVaulesChanged();
            }
        }
        private global::System.String _Vaules;
        partial void OnVaulesChanging(global::System.String value);
        partial void OnVaulesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    
    }

    #endregion

    
}
